# https://golangci-lint.run/docs/configuration/file/
# See the dedicated "version" documentation section.
version: "2"
linters:
  enable:
    # For when I decide to deal with some TODO: or FIXME:
    # - godox
    - copyloopvar
    - dupl
    - errcheck
    - exptostd
    - funcorder
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - maintidx
    - makezero
    - mirror
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testpackage
    - usestdlibvars
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - composites
        # the following can be usefull to enable from time to time
        # https://medium.com/@sebassegros/golang-dealing-with-maligned-structs-9b77bacf4b97
        # https://en.wikipedia.org/wiki/Data_structure_alignment
        # https://go.dev/src/go/types/sizes.go
        # - fieldalignment
    errcheck:
      # See https://github.com/kisielk/errcheck#excluding-functions
      exclude-functions:
        - "(*os.File).Close"
        - "(*sqlx.Tx).Rollback"

    gocognit:
      # Minimal code complexity to report.
      # Default: 30 (but we recommend 10-20)
      min-complexity: 15
    gosec:
      # To specify a set of rules to explicitly exclude.
      # Available rules: https://github.com/securego/gosec#available-rules
      # Default: []
      excludes:
        # But (*strings.Builder).WriteString() returns always a nil error.
        - G104 # Audit errors not checked
