# https://golangci-lint.run/docs/configuration/file/
# See the dedicated "version" documentation section.
version: "2"
linters:
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - dupl
    - exptostd
    - funcorder
    - funlen
    - gocognit
    - gocyclo
    - godot
    # For when I decide to deal with some TODO: or FIXME:
    # - godox
    - gosec
    - iface
    - importas
    - interfacebloat
    - intrange
    - maintidx
    - makezero
    - mirror
    - perfsprint
    - prealloc
    - predeclared
    - testableexamples
    - testpackage
    - usestdlibvars
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - composites
        # the following can be usefull to enable from time to time
        # https://medium.com/@sebassegros/golang-dealing-with-maligned-structs-9b77bacf4b97
        # https://en.wikipedia.org/wiki/Data_structure_alignment
        # https://go.dev/src/go/types/sizes.go
        # - fieldalignment

